language: java

jdk:
  - oraclejdk8

sudo: required

services:
  - docker

before_install:
  - cd docker/dev
  - docker-compose up -d
  - docker ps -a

before_script:
  - cd ../../src

script:
  - mvn package
  - mvn test
  - mvn test -Ptest-business
  - mvn test -Ptest-consumer
